Set message
JuliaJakoubek/MaintenanceMonitor pull request #18
Opened 2022-06-25 16:04 UTC by JuliaJakoubek

2022-06-25 16:18 UTC, JuliaJakoubek commented
changeStatus & changemessage renamed with setStatus & setMessage
StateController final
Statecontroller Test für Request (bin mir nicht sicher ob das wirklich passt!)

2022-06-26 11:19 UTC, DataWi requested changes
Unit tests sollten korregiert werden - mit diesen tests schlägt der build fehl

2022-06-26 11:19 UTC, DataWi commented on src/test/java/at/technikum/maintenancemonitor/ControllerTests/StateControllerTests.java
> +        httpURLConnection.setRequestMethod("POST");
Die Tests sehen per se gut aus - aber der build zeigt, dass er fehlschlägt mit "connection refused".
Ich vermute, bei status/set sollten wir kein post Mapping testen -> da die Anforderung ja keine Payload hat, wird es hier ein GET Request sein.

Haben die Unit Tests bei dir lokal geklappt?

2022-06-26 17:31 UTC, DataWi approved these changes

2022-06-26 18:21 UTC, closed without merging